name: "Rust Cache"
description: "A GitHub Action that implements smart caching for rust/cargo projects with sensible defaults."
author: "Arpad Borsos <arpad.borsos@googlemail.com>"
inputs:
  key:
    description: "An additional key for the cache"
    required: false
  working-directory:
    description: "The working directory this action should operate in"
    required: false
outputs:
  cache-hit:
    description: 'A boolean value that indicates an exact match was found'
runs:
  using: "node12"
  main: "dist/restore/index.js"
  post: "dist/save/index.js"
  post-if: "success()"
branding:
  icon: "archive"
  color: "gray-dark"
